

export const Networkdata = [
    {
        name:'PATIENT1',
        age:'123',
        bed:'1',
        status:'ACTIVATED',
        btncolor:'success',
        redirect:'/networks/network1'
    },
    {
        name:'PATIENT2',
        age:'123',
        bed:'1',
        status:'DEACTIVATED',
        btncolor:'error',
        redirect:'/networks/network2'
    },
    {
        name:'PATIENT3',
        age:'123',
        bed:'1',
        status:'DEACTIVATED',
        btncolor:'error',
        redirect:'/networks/network3'
    },
    {
        name:'PATIENT4',
        age:'123',
        bed:'1',
        status:'DEACTIVATED',
        btncolor:'error',
        redirect:'/networks/network4'
    },
    {
        name:'PATIENT5',
        age:'123',
        bed:'1',
        status:'DEACTIVATED',
        btncolor:'error',
        redirect:'/networks/network5'
    },
    {
        name:'PATIENT6',
        age:'123',
        bed:'1',
        status:'DEACTIVATED',
        btncolor:'error',
        redirect:'/networks/network6'
    },
    {
        name:'PATIENT7',
        age:'123',
        bed:'1',
        status:'DEACTIVATED',
        btncolor:'error',
        redirect:'/networks/network7'
    },
    {
        name:'PATIENT8',
        age:'123',
        bed:'1',
        status:'DEACTIVATED',
        btncolor:'error',
        redirect:'/networks/network8'
    },
    {
        name:'PATIENT9',
        age:'123',
        bed:'1',
        status:'DEACTIVATED',
        btncolor:'error',
        redirect:'/networks/network9'
    },
    {
        name:'PATIENT10',
        age:'123',
        bed:'1',
        status:'DEACTIVATED',
        btncolor:'error',
        redirect:'/networks/network10'
    },
    
]